app = "immigration-rag-frontend"
primary_region = "syd"

[build]
  dockerfile = "../Dockerfile.frontend"

[env]
  VITE_API_URL = "https://immigration-rag-backend.fly.dev/api"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512"  # Static site needs less memory
