version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: immigration-rag-backend
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - CORS_ORIGINS=*
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - DATA_DIR=/app/data
      - DOCUMENTS_DIR=/app/data/immigration_docs
      - PORT=${PORT:-8000}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: immigration-rag-frontend
    ports:
      - "${PORT:-80}:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  data:
    driver: local

