app = "immigration-rag-backend"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile.backend"

[env]
  PORT = "8000"
  HF_TOKEN = "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"
  CORS_ORIGINS = "*"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "performance-2x"
  memory = "4096"  # 4GB RAM for ML workloads
  cpu_kind = "shared"

[mounts]
  source = "rag_data"
  destination = "/app/data"
